spring.application.name=backend

# ===================================================================
# 1. DATABASE NETWORK CONNECTION
# ===================================================================
spring.datasource.url=jdbc:postgresql://localhost:5432/proctor_saas
spring.datasource.username=postgres
spring.datasource.password=postgre
spring.datasource.driver-class-name=org.postgresql.Driver

# ===================================================================
# 2. OBJECT RELATIONAL MAPPING (JPA / HIBERNATE) CONFIGURATION
# ===================================================================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# ===================================================================
# 3. CONSOLE DEBBUGGING LOGS
# ===================================================================
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true